# Generated by Django 5.2.8 on 2025-11-24 19:38

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(max_length=100)),
                ('race', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.CharField(blank=True, max_length=50, null=True)),
                ('sex', models.CharField(blank=True, max_length=20, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('medical_observations', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pets/')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=2, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scheduling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_scheduling', models.DateField()),
                ('status', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=20)),
                ('observations', models.TextField(blank=True, null=True)),
                ('percentage_discount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('gross_total_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daycare.pet')),
                ('services', models.ManyToManyField(to='daycare.service')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('note_number', models.AutoField(primary_key=True, serialize=False)),
                ('issue_date', models.DateTimeField(auto_now_add=True)),
                ('scheduling', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='daycare.scheduling')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daycare.state')),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('know', models.CharField(blank=True, choices=[('internet', 'Internet'), ('amigo', 'Amigo'), ('indicacao_veterinario', 'Indicação de Veterinário'), ('redes_sociais', 'Redes Sociais'), ('panfleto', 'Panfleto / Outdoor'), ('passando_na_rua', 'Passando na Rua'), ('evento_pet', 'Evento Pet'), ('outro', 'Outro')], max_length=50, null=True)),
                ('city', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='state', chained_model_field='state', null=True, on_delete=django.db.models.deletion.SET_NULL, to='daycare.city')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='daycare.state')),
            ],
        ),
        migrations.AddField(
            model_name='scheduling',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daycare.tutor'),
        ),
        migrations.AddField(
            model_name='pet',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daycare.tutor'),
        ),
    ]
