# Generated by Django 5.2.8 on 2025-11-25 11:57

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daycare', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pet',
            options={'verbose_name': 'Pet', 'verbose_name_plural': 'Pets'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Serviço', 'verbose_name_plural': 'Serviços'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'verbose_name': 'Estado', 'verbose_name_plural': 'Estados'},
        ),
        migrations.AlterModelOptions(
            name='tutor',
            options={'verbose_name': 'Tutor', 'verbose_name_plural': 'Tutores'},
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daycare.state', verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Idade'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='medical_observations',
            field=models.TextField(blank=True, null=True, verbose_name='Observações Médicas'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='pets/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='race',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Raça'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='sex',
            field=models.CharField(blank=True, choices=[('macho', 'Macho'), ('femea', 'Fêmea')], max_length=20, null=True, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.CharField(max_length=100, verbose_name='Espécie'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daycare.tutor', verbose_name='Tutor'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Peso'),
        ),
        migrations.AlterField(
            model_name='scheduling',
            name='date_scheduling',
            field=models.DateField(verbose_name='Data do Agendamento'),
        ),
        migrations.AlterField(
            model_name='scheduling',
            name='gross_total_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Bruto Total'),
        ),
        migrations.AlterField(
            model_name='scheduling',
            name='observations',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='scheduling',
            name='percentage_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Desconto Percentual'),
        ),
        migrations.AlterField(
            model_name='scheduling',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daycare.pet', verbose_name='Pet'),
        ),
        migrations.AlterField(
            model_name='scheduling',
            name='services',
            field=models.ManyToManyField(to='daycare.service', verbose_name='Serviços'),
        ),
        migrations.AlterField(
            model_name='scheduling',
            name='status',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=20, verbose_name='Status de Pagamento'),
        ),
        migrations.AlterField(
            model_name='scheduling',
            name='total_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Total'),
        ),
        migrations.AlterField(
            model_name='scheduling',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daycare.tutor', verbose_name='Tutor'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='state',
            name='abbreviation',
            field=models.CharField(max_length=2, unique=True, verbose_name='Sigla'),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='city',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='state', chained_model_field='state', null=True, on_delete=django.db.models.deletion.SET_NULL, to='daycare.city', verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='know',
            field=models.CharField(blank=True, choices=[('internet', 'Internet'), ('amigo', 'Amigo'), ('indicacao_veterinario', 'Indicação de Veterinário'), ('redes_sociais', 'Redes Sociais'), ('panfleto', 'Panfleto / Outdoor'), ('passando_na_rua', 'Passando na Rua'), ('evento_pet', 'Evento Pet'), ('outro', 'Outro')], max_length=50, null=True, verbose_name='Como Conheceu'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='daycare.state', verbose_name='Estado'),
        ),
    ]
