# Generated by Django 5.2.8 on 2025-11-25 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daycare', '0002_alter_pet_options_alter_service_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Cidade', 'verbose_name_plural': 'Cidades'},
        ),
        migrations.AlterModelOptions(
            name='scheduling',
            options={'verbose_name': 'Agendamento', 'verbose_name_plural': 'Agendamentos'},
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='sex',
            field=models.CharField(blank=True, choices=[('macho', 'Macho'), ('femea', 'Fêmea')], default='macho', max_length=20, verbose_name='Sexo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pet',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daycare.tutor', verbose_name='Nome do Tutor'),
        ),
        migrations.AlterField(
            model_name='scheduling',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daycare.pet', verbose_name='Nome do Pet'),
        ),
        migrations.AlterField(
            model_name='scheduling',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daycare.tutor', verbose_name='Nome do Tutor'),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Estado'),
        ),
    ]
