# Generated by Django 5.2.8 on 2025-11-25 19:06

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daycare', '0003_alter_city_options_alter_scheduling_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'verbose_name': 'Nota de Atendimento', 'verbose_name_plural': 'Notas'},
        ),
        migrations.AlterField(
            model_name='note',
            name='issue_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Emissão'),
        ),
        migrations.AlterField(
            model_name='note',
            name='note_number',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Numero da Nota'),
        ),
        migrations.AlterField(
            model_name='note',
            name='scheduling',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='daycare.scheduling', verbose_name='Agendamento'),
        ),
        migrations.AlterField(
            model_name='scheduling',
            name='pet',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='tutor', chained_model_field='tutor', on_delete=django.db.models.deletion.CASCADE, to='daycare.pet', verbose_name='Nome do Pet'),
        ),
    ]
